name: test

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PRESTO_VERSION: 340

    steps:
    - uses: actions/checkout@v2

    - name: fetch dependency
      run:  curl -LO https://github.com/IBM/presto-db2/releases/download/$PRESTO_VERSION/presto-db2-$PRESTO_VERSION.zip

    - name: prepare dependency
      run: unzip presto-db2-${PRESTO_VERSION}.zip
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        repository: shawnzhu/prestodb
        tags: test-only
        push: false
        build_args: PRESTO_VERSION=$PRESTO_VERSION

    - uses: brpaz/structure-tests-action@v1.1.2
      with:
        image: "shawnzhu/prestodb:test-only"
        configFile: test_config.yaml
